network:
  version: 2
  ethernets:
    ens3:
      dhcp4: false
      addresses: [10.6.93.130/28]
      routes:
        - to: default
          via: 10.6.93.129
      nameservers:
        addresses: [8.8.8.8]
